// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW72s1QYWIofIYKyGInuOiQ7enTm9VUXo',
    appId: '1:37024419134:web:4bd8b5e585e70db9a5706f',
    messagingSenderId: '37024419134',
    projectId: 'flutter-95e6a',
    authDomain: 'flutter-95e6a.firebaseapp.com',
    storageBucket: 'flutter-95e6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6oc5AphAoxdYlvBZvGilrb65hW59vYA',
    appId: '1:37024419134:android:50b13b906cad464da5706f',
    messagingSenderId: '37024419134',
    projectId: 'flutter-95e6a',
    storageBucket: 'flutter-95e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52WNuoSqtEzv3aPtM6U9NzCwNw-DZW9I',
    appId: '1:37024419134:ios:c89378051e0fa521a5706f',
    messagingSenderId: '37024419134',
    projectId: 'flutter-95e6a',
    storageBucket: 'flutter-95e6a.firebasestorage.app',
    iosBundleId: 'com.example.msDreamsDelights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA52WNuoSqtEzv3aPtM6U9NzCwNw-DZW9I',
    appId: '1:37024419134:ios:c89378051e0fa521a5706f',
    messagingSenderId: '37024419134',
    projectId: 'flutter-95e6a',
    storageBucket: 'flutter-95e6a.firebasestorage.app',
    iosBundleId: 'com.example.msDreamsDelights',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW72s1QYWIofIYKyGInuOiQ7enTm9VUXo',
    appId: '1:37024419134:web:d007006cc9360200a5706f',
    messagingSenderId: '37024419134',
    projectId: 'flutter-95e6a',
    authDomain: 'flutter-95e6a.firebaseapp.com',
    storageBucket: 'flutter-95e6a.firebasestorage.app',
  );
}
